### Create a post
POST http://localhost:3000/api/orders
Content-Type: application/json

{
  "userId": "abc123",
  "totalPrice": 10293,
  "isShipped": false,
  "address": {
    "firstName": "C",
    "lastName": "Margarito",
    "email": "carlito@gmail.com",
    "zipCode": "12345",
    "city": "New York",
    "street": "testgatan 31",
    "phoneNumber": "0707433677"
  },
  "orderItems": [
    {
      "id": "1334h",
      "image": "http://hej.jpeg",
      "title": "Hej",
      "description": "Hej",
      "price": 100,
      "stock": 10,
      "quantity": 1
    }
  ]
}





