### Retrieve product
GET http://localhost:3000/api/products/646bd0534eb83ae87d4731d1

### Retrieve all products
GET http://localhost:3000/api/products

### Delete product
DELETE http://localhost:3000/api/products/646bd0534eb83ae87d4731d1

### Update product
PUT http://localhost:3000/api/products/646bd0534eb83ae87d4731d1
Content-Type: application/json

{
    "image": "new_image_id",
    "title": "New Product Title",
    "description": "Updated Product Description",
    "price": 149.99,
    "stock": 20
}

### Create product
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "categories": ["646df95e71bd5c21bc6338d3", "646f1ad90cdb050fa55030da"],
    "image": "646c6c2a4eb83ae87d473201",
    "title": "PowerBook 13",
    "description": "The PowerBook 13 is the perfect laptop for students and creative professionals. With its compact size and powerful performance, you can take your work wherever you go. The 13-inch Retina display delivers crisp and clear visuals, while the powerful processor ensures speedy performance.",
    "price": 3919,
    "stock": 0
}