
### Get a list of all users

GET http://localhost:3000/api/users


### Create user

POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "email": "newuser@mejc.com",
    "password": "hashedpassword"
}


### Login as user

POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "user@mejc.com",
    "password": "hashedpassword"
}

### Login as admin

POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "admin@mejc.com",
    "password": "hashedpassword"
}


### Logout user

POST http://localhost:3000/api/users/logout