export const mockOrders = [
    {
      _id: 'orderId1',
      userId: 'userId1',
      deliveryAddress: {
        _id: 'addressId1',
        fullName: 'John Doe',
        firstName: 'John',
        lastName: 'Doe',
        email: 'john.doe@example.com',
        street: '123 Main St',
        city: 'New York',
        zipCode: 10001,
        phoneNumber: 1234567890,
      },
      orderItems: [
        { _id: 'orderItemId1', productId: 'productId1', quantity: 1 },
        { _id: 'orderItemId2', productId: 'productId2', quantity: 2 },
      ],
      createdAt: new Date(),
      isShipped: false,
      totalPrice: 300,
    },
    {
      _id: 'orderId2',
      userId: 'userId2',
      deliveryAddress: {
        _id: 'addressId2',
        fullName: 'Jane Smith',
        firstName: 'Jane',
        lastName: 'Smith',
        email: 'jane.smith@example.com',
        street: '456 Market St',
        city: 'San Francisco',
        zipCode: 94104,
        phoneNumber: 2345678901,
      },
      orderItems: [
        { _id: 'orderItemId3', productId: 'productId3', quantity: 1 },
      ],
      createdAt: new Date(),
      isShipped: true,
      totalPrice: 200,
    },
    {
      _id: 'orderId3',
      userId: 'userId3',
      deliveryAddress: {
        _id: 'addressId3',
        fullName: 'Bob Johnson',
        firstName: 'Bob',
        lastName: 'Johnson',
        email: 'bob.johnson@example.com',
        street: '789 Broadway St',
        city: 'Chicago',
        zipCode: 60601,
        phoneNumber: 3456789012,
      },
      orderItems: [
        { _id: 'orderItemId4', productId: 'productId1', quantity: 3 },
        { _id: 'orderItemId5', productId: 'productId4', quantity: 1 },
      ],
      createdAt: new Date(),
      isShipped: false,
      totalPrice: 500,
    },
  ];